### ISSUE TITLE
method 'setBackgroundHandler' isn't defined for the type 'FlutterUploader'

### ISSUE THREAD

**Issue by nkenna** [fluttercommunity/flutter_uploader#226]
It seems setBackgroundHandler cannot be accessed from FlutterUploader()
I did copy the example code and still got this error.

The method 'setBackgroundHandler' isn't defined for the type 'FlutterUploader'.
Try correcting the name to the name of an existing method, or defining a method named 'setBackgroundHandler'.

`FlutterUploader _uploader = FlutterUploader();`
` @override
  void initState() {    
    super.initState();
 
    _uploader.setBackgroundHandler(uploaderBackgroundHandler);
    WidgetsBinding.instance.addObserver(this);

  }`

**Comment by spatialbits** [comment]
You'll need one of the beta releases, not the one in dart pub.

eg Pubspec.yaml
```yml
  flutter_uploader:
    git: 
      url: git@github.com:fluttercommunity/flutter_uploader.git
      tag: 2.0.0-beta.6
```
